
version: '3.8'

services:
  api:
    build: ./DashboardAPI
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings:SQLConnection=Server=db;Database=MesMetrics;User=sa;Password=Your_password123;

  frontend:
    build: ./DashboardFrontend
    ports:
      - "5001:80"
    depends_on:
      - api

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
